### ISSUE TITLE
Getting error when installing the module

### ISSUE THREAD

**Issue by MohammedSalahadin** [PopulateTools/decidim-module-anonymous_proposals#6]
I'm facing this error when I run bundle:
```
Fetching https://github.com/PopulateTools/decidim-module-anonymous_proposals
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies......
Bundler could not find compatible versions for gem "decidim-core":
  In snapshot (Gemfile.lock):
    decidim-core (= 0.23.1)

  In Gemfile:
    decidim-dev (= 0.23.1) was resolved to 0.23.1, which depends on
      decidim (= 0.23.1) was resolved to 0.23.1, which depends on
        decidim-core (= 0.23.1)

    decidim-anonymous_proposals was resolved to 0.1, which depends on
      decidim-core (>= 0.24.0)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```
I have tried bundle update with no avail.

**Comment by entantoencuanto** [comment]
Hi, @MohammedSalahadin, unfortunately the module is not compatible with the 0.23 release after recent changes made in #4. I recommend you to upgrade decidim to 0.24 [latest stable release](https://github.com/decidim/decidim/releases/tag/v0.24.3) if possible, because even if the version requirement was not set, the module would fail with 0.23.

**Comment by MohammedSalahadin** [comment]
Hi, @entantoencuanto  Thanks for you reply, I upgraded my decidim using ```rake decidim:upgrade``` command followed by ```bundle update decidim``` command then all the decidim system have been infected and it's not working anymore.
When I access any the pages in the control panel I get an error says ```There was a problem with our server``` as you can see in the picture below:
![1](https://user-images.githubusercontent.com/60615635/124820349-0e100d00-df76-11eb-92f7-f7fb87fcf640.PNG)
Then I have tried to run ```bundle update``` command and I have got the following error:
![2](https://user-images.githubusercontent.com/60615635/124820863-b02ff500-df76-11eb-8a03-f4f9303accf7.PNG)

Nothing works, Everything stopped working LOL.

**Comment by entantoencuanto** [comment]
Take a look at the failing dependencies and run decidim:upgrade at the end of the process. Remember to run migrations introduced by the upgrade tasks, the exception may be related with pending migrations

**Comment by MohammedSalahadin** [comment]
What exactly " failing dependencies "   means, what are the commands that I should run for that?
What command is used to run migrations introduced by the upgrade tasks?
_
